[package]
name = "reqsign-azure-storage"
version = "0.1.0"

categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
form_urlencoded.workspace = true
http.workspace = true
log.workspace = true
percent-encoding.workspace = true
reqsign-core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true


[dev-dependencies]
dotenv.workspace = true
env_logger.workspace = true
reqwest = { workspace = true, features = ["rustls-tls"] }
tokio = { workspace = true, features = ["full"] }
