// Env values used in tencent services.
pub const TENCENT_CLOUD_ACCESS_KEY_ID: &str = "TENCENT_CLOUD_ACCESS_KEY_ID";
pub const TENCENT_CLOUD_ACCESS_KEY_SECRET: &str = "TENCENT_CLOUD_ACCESS_KEY_SECRET";
pub const TENCENT_CLOUD_SECRET_TOKEN: &str = "TENCENT_CLOUD_SECRET_TOKEN";
