[package]
name = "reqsign"
version = "0.17.0"

edition.workspace = true
license.workspace = true
repository.workspace = true

description = "Signing HTTP requests for AWS, Azure, Google, Huawei, Aliyun, Tencent and Oracle services"
keywords = ["http", "requests", "signing", "aws", "azure"]
categories = ["authentication", "web-programming::http-client"]

[dependencies]
# Core functionality (always included)
reqsign-core = { version = "0.16", path = "../core" }

# Service implementations (optional)
reqsign-aliyun-oss = { version = "0.1", path = "../services/aliyun-oss", optional = true }
reqsign-aws-v4 = { version = "0.1", path = "../services/aws-v4", optional = true }
reqsign-azure-storage = { version = "0.1", path = "../services/azure-storage", optional = true }
reqsign-google = { version = "0.1", path = "../services/google", optional = true }
reqsign-huaweicloud-obs = { version = "0.1", path = "../services/huaweicloud-obs", optional = true }
reqsign-oracle = { version = "0.1", path = "../services/oracle", optional = true }
reqsign-tencent-cos = { version = "0.1", path = "../services/tencent-cos", optional = true }

# Context implementations (optional but included by default)
reqsign-file-read-tokio = { version = "0.1", path = "../context/file-read-tokio", optional = true }
reqsign-http-send-reqwest = { version = "0.1", path = "../context/http-send-reqwest", optional = true }

# Direct dependencies for default context
anyhow = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
bytes = { version = "1", optional = true }
home = { version = "0.5", optional = true }
http = { version = "1", optional = true }
reqwest = { version = "0.12", optional = true, default-features = false }
tokio = { version = "1", optional = true, features = ["fs"] }

[features]
default = ["default-context"]
default-context = ["dep:reqsign-file-read-tokio", "dep:reqsign-http-send-reqwest", "dep:anyhow", "dep:async-trait", "dep:bytes", "dep:home", "dep:http", "dep:reqwest", "dep:tokio"]

# Service features
aliyun = ["dep:reqsign-aliyun-oss"]
aws = ["dep:reqsign-aws-v4"]
azure = ["dep:reqsign-azure-storage"]
google = ["dep:reqsign-google"]
huaweicloud = ["dep:reqsign-huaweicloud-obs"]
oracle = ["dep:reqsign-oracle"]
tencent = ["dep:reqsign-tencent-cos"]

# Full feature set
full = ["aliyun", "aws", "azure", "google", "huaweicloud", "oracle", "tencent"]

# Advanced features for custom context implementations
custom-context = []

[dev-dependencies]
env_logger = "0.11"
tempfile = "3"
tokio = { version = "1", features = ["full"] }

[[example]]
name = "aws"
required-features = ["aws", "default-context"]

[[example]]
name = "azure"
required-features = ["azure", "default-context"]

[[example]]
name = "google"
required-features = ["google", "default-context"]